### ISSUE TITLE
Doesn't work if CiviCRM is not installed in domain root

### ISSUE THREAD

**Issue by systopia** [systopia/de.systopia.recentitems#1]
CiviCRM is sometimes installed in a subfolder, e.g.:
```
https://my.domain.org/crm/civicrm/dashboard
```
In this case the links coming in to the build function (https://github.com/systopia/de.systopia.recentitems/blob/0.2/CRM/Recentitems/Utils.php#L41-L72) contains the ``/crm/`` prefix, so the ``ltrim`` doesn't work properly and generates bad links.

**Comment by jensschuppe** [comment]
@systopia Passing absolute URLs (with the base URL) should work, although there is something going wrong within `CRM_Core_BAO_Navigation::getMenuName()` when passing server-absolute URLs (starting with `/`), as `CRM_Utils_System::url()` expects the path not being prefixed with a `/`.

Could you try 7e5a1dbfd9899b765ab63cdfad09feda5c8cd50e?

**Comment by systopia** [comment]
> Could you try 7e5a1db?

Nope, doesn't work for me. I have created an alternative fix, see https://github.com/systopia/de.systopia.recentitems/commit/8954b75b2124fcda01750ba4a50d3f01a8e99445.

@jensschuppe: Does this work for you? What do you think?

**Comment by jensschuppe** [comment]
@systopia Whithout having that one tested: What if the CiviCRM installation has a path prefix containing `civicrm/`, so that the path would be like `https://example.org/civicrm/civicrm` or `https://example.org/whatever-prefixes-civicrm/civicrm`? `strpos()` would then match the first occurence and break the path.

**Comment by systopia** [comment]
Yes, I thought about this, too. But I would say we neglect this scenario for the sake of simplicity. For now, anyway.

**Comment by systopia** [comment]
Unless you have a quick and simple solution that works in all cases, of course...

**Comment by systopia** [comment]
Nope, that actually makes it worse, the resulting link is 
```
http://host/prefix/prefix/civicrm/contact/view?reset=1&cid=3
```

Let's just use https://github.com/systopia/de.systopia.recentitems/commit/8954b75b2124fcda01750ba4a50d3f01a8e99445 if it works for you. @jensschuppe Could you test that?

**Comment by jensschuppe** [comment]
@systopia Noticed that just after pushing, https://github.com/systopia/de.systopia.recentitems/tree/dev_1_alt1 should cover all scenarios.

**Comment by jensschuppe** [comment]
Successfully tested branch [dev_1_alt](https://github.com/systopia/de.systopia.recentitems/tree/dev_1_alt1) with a CiviCRM installation in a sub directory.
