### ISSUE TITLE
Only works with "administer CiviCRM" permission

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.recentitems#2]
Should instead require `access CiviCRM` permission, as the original block did not require any permission at all.

**Comment by systopia** [comment]
@jensschuppe I fully agree. Is the only reason that the permissions for the API call hasn't be set? Do you want me to have a look?

**Comment by jensschuppe** [comment]
@systopia Seems to work with 79a280b39e7dc8a513eb348c7c16279e1ecb4df6, would be nice you having a look as well.

**Comment by systopia** [comment]
@jensschuppe Looks good to me...
